players:
- active: true
  name: Konaté
  url: https://www.futbin.com/26/player/251/ibrahima-konate
- active: true
  alert_above: 0
  alert_below: null
  alert_user_id: 416353640073134082
  category: Allgemein
  name: Kane
  url: https://www.futbin.com/26/player/18919/harry-kane
- active: true
  name: Karchaoui
  url: https://www.futbin.com/26/player/104/sakina-karchaoui
- active: true
  name: Abedi Pelé
  url: https://www.futbin.com/26/player/18820/ayew
- active: true
  name: Saliba
  url: https://www.futbin.com/26/player/225/william-saliba
- active: true
  name: Marcos Llorente
  url: https://www.futbin.com/26/player/18924/marcos-llorente-moreno
- active: true
  name: Hakimi
  url: https://www.futbin.com/26/player/91/achraf-hakimi
- active: true
  name: Frimpong
  url: https://www.futbin.com/26/player/331/jeremie-frimpong
- active: true
  name: Marmoush
  url: https://www.futbin.com/26/player/417/omar-marmoush
settings:
  dashboard_channel_id: 1419372663985541150
  dashboard_message_id: 1420401194886762557
  global_threshold_percent: 5
  platform: ps
